// src/Header.tsx
import 'tippy.js/dist/tippy.css';

function Header() {
	const githubUsername: string =
		import.meta.env.VITE_GITHUB_ACTOR || 'your_username';

	return (
		<header className="text-center py-4 flex items-center justify-center">
			<img
				src="/avatar.png"
				alt="GitHub Avatar"
				className="w-20 h-20 rounded-full border-2 border-gray-300 dark:border-gray-600 flex items-center"
			/>
			<div className="flex flex-col text-left pl-4">
				<h1 className="text-4xl font-bold">
					<a
						href={`https://github.com/${githubUsername}`}
						target="_blank"
						rel="noopener noreferrer"
						className="hover:text-blue-500 dark:hover:text-blue-400"
					>
						{githubUsername}
					</a>
					's Sites
				</h1>
				<p className="text-lg mt-2 text-gray-600 dark:text-gray-400">
					A list of my projects that have a GitHub Pages site.
				</p>
			</div>
		</header>
	);
}

export default Header;

// src/Header.vue
<template>
	<header class="text-center py-4 space-y-2">
		<div class="flex items-center justify-center">
			<img src="/avatar.png" alt="GitHub Avatar"
				class="w-20 h-20 rounded-full border-2 border-gray-300 dark:border-gray-600 flex items-center" />
			<div class="flex flex-col text-left pl-4">
				<h1 class="text-4xl font-bold"> {{ titleParts[0] }}<a v-if="titleParts[1] !== undefined"
						:href="`https://github.com/${cfg.ghUsername}`" target="_blank" rel="noopener noreferrer"
						class="hover:text-blue-500 dark:hover:text-blue-400">{{ cfg.ghUsername }}</a>{{ titleParts[1] }} </h1>
				<p v-if="cfg.headerText" class="text-lg mt-2 text-gray-600 dark:text-gray-400"> {{ cfg.headerText }} </p>
			</div>
		</div>
		<div v-if="cfg.links && cfg.links.length > 0" class="flex justify-center space-x-4 py-2">
			<a v-for="link in cfg.links" :key="link.url" :href="link.url" target="_blank" rel="noopener noreferrer"
				class="text-gray-600 dark:text-gray-400 hover:text-blue-500 dark:hover:text-blue-400 flex items-center space-x-1">
				<Icon v-if="link.icon" :name="link.icon" />
				<span v-if="link.name">{{ link.name }}</span>
			</a>
		</div>
	</header>
</template>
<script setup lang="ts">
import { useConfigStore } from './stores/config'
import { computed } from 'vue'
import Icon from './components/Icon.vue';

const cfg = useConfigStore()

const titleParts = computed(() => {
	const title = cfg.siteTitle;
	const username = cfg.ghUsername;
	if (title.includes(username)) {
		return title.split(username);
	}
	return [title];
})
</script>
